<?php
// config.php

// IP/hostname of the ATS-Mini (the default hostanme is atsmini.local).
// The IP is the one generated by the ats mini AP, after configuration and connection to a router, you can specify the IP assigned by the router 
define('ATSMINI_BASE_URL', 'http://10.1.1.1');
